### ISSUE TITLE
how did the program perform densification?

### ISSUE THREAD

**Issue by NeutrinoLiu** [markomih/SplatFields#4]
nice work. I have a small question. 
since all attributes except xyz are derived from MLP, it seems the xyz is the only thing that should be updated when performing densification/pruning. Why you still clone and prune other attributes ?
https://github.com/markomih/SplatFields/blob/bfae2228c8cbff53ce0933119aa05cf29eaeaca9/scene/gaussian_model.py#L334

**Comment by markomih** [comment]
Hi @NeutrinoLiu,

Good point, and you're absolutely right—it doesn’t impact the overall performance. We retained it mainly because the codebase is based on the original 3DGS code, and we haven't prioritized removing it yet. However, it's something we can clean up in future versions.

Best,
Marko
