### ISSUE TITLE
About 'run_blender.sh'

### ISSUE THREAD

**Issue by Morikunn** [markomih/SplatFields#6]
This's a really wonderful work! 
I have a question about  'run_blender.sh', if I want to apply on blender dataset such as nerf_synthesie (static) or dnerf (dynamic), should I first use 3DGS to get initialization Gaussian center points for SplatFields training process? 
In other words, could SplatFields achieve reconstruction if I set '--pts_samples random' on blender dataset without 3DGS?

**Comment by markomih** [comment]
Hi @Morikunn,

Thank you for your interest in SplatFields! Apologies for the delayed response—I missed your comment earlier.

Using random point initialization would likely yield suboptimal results, as SplatFields is not well-suited for pruning points that are poorly initialized. However, this option is supported in the codebase if you’d like to benchmark its performance. You can find the relevant implementation here: [link](https://github.com/markomih/SplatFields/blob/main/scene/dataset_readers.py#L783).

Let me know if you have further questions or need assistance!

Best,
Marko
